const endpointMap = {
    '100-create-user': 'createUser',
    '101-update-user': 'updateUser',
    '102-login': 'login',
    '103-get-user-info': 'getUserInfo',
    '110-create-task': 'createTask',
    '111-update-status-tasks': 'updateStatusTasks',
    '112-update-task': 'UpdateTask',
    '113-list-individual-task-by-status': 'listIndividualTaskByStatus',
    '114-delete-tasks':'deleteTasks',
    '115-list-task-by-sprint':'listTaskBySprint',
    '116-upload-photo':'uploadPhoto',
    '117-list-task-by-group-status':'listTaskByGroupStatus',
    '118-create-group':'createGroup',
    '119-update-group':'updateGroup',
    '120-delete-group':'deleteGroup',
    '121-list-my-group':'listMyGroup',
    '122-get-group-detail':'getGroupDetail',
    '123-join-group':'joinGroup',
    '124-approve-request':'approveRequest',
    '125-remove-request':'removeRequest',
    '126-ban-member':'banMember',
    '127-list-member-by-group':'listMemberByGroup',
    '128-update-member-role':'UpdateMemberRole',
    '129-leave-group': 'leaveGroup',
    '130-add-member-group': 'addMemberGroup',
    '140-create-sprint-group': 'createSprintGroup',
    '141-update-sprint-group': 'updateSprintGroup',
    '142-get-sprint-by-group': 'getSprintByGroup',
    '143-get-sprint-detail': 'getSprintDetail',
}

module.exports = endpointMap